[workspace]
members = [
    "contracts/interchain-interceptor",
    "contracts/interchain-interceptor-authz",
    "contracts/stargate-poc",
    "packages/interchain-interceptor-base",
]

[workspace.dependencies]
cw-ownable = "0.5.1"
thiserror = "1.0.50"

[profile.release]
rpath = false
lto = true
overflow-checks = true
