[workspace]
members = [
    "contracts/interchain-interceptor",
    "contracts/interchain-interceptor-authz",
    "contracts/token",
    "packages/interchain-interceptor-base"
]
resolver = "2"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[workspace.dependencies]
cosmwasm-std    = { version = "1.5.0", default-features = false }
cosmwasm-schema = { version = "1.5.0", default-features = false }
cw-storage-plus = { version = "1.2.0", default-features = false }
cw2             = { version = "1.1.2", default-features = false }
cw-utils        = { version = "1.0.3", default-features = false }
neutron-sdk     = { git = "https://github.com/neutron-org/neutron-sdk", branch = "sdk/47", default-features = false }
cw-ownable      = "0.5.1"
thiserror       = "1.0.50"
