[workspace]
members = ["contracts/interchain-interceptor", "contracts/interchain-interceptor-authz", "packages/interchain-interceptor-base"]

[workspace.dependencies]
cw-ownable      = "0.5.1"

[profile.release]
rpath = false
lto = true
overflow-checks = true
